# Site settings
title: amisrs
description: Stuff done by amisrs.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: amisrs
user_description: Just keep trying.  
user_title: Indie Developer & Artist
email: amisrs@amisrs.com
twitter_username: amisrs
github_username:  amisrs
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
